version: '3'

services:

  database:
    image: mysql:5.7
    container_name: 
      "database"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./db_data/crud.sql:/docker-entrypoint-initdb.d/init.sql

  pma:
    image: phpmyadmin
    container_name:
      "pma"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
    ports:
      - '8080:80'

##> doctrine/doctrine-bundle ###