controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_user_controller:
    path: /
    controller: App\Controller\UserController::userAction
    methods: 'GET'
